    
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: atomic-hyprland
description: Atomic immutable Fedora core + Hyprland + NVIDIA Drivers
base-image: ghcr.io/ublue-os/base-nvidia
image-version: 42

modules:
  - type: rpm-ostree
    install:
      - hyprland
      - xdg-desktop-portal-hyprland
      - polkit-gnome
      - sddm
      - kitty
      - wofi
      - waybar
      - gparted
      - pavucontrol
      - libva-nvidia-driver

  - type: systemd
    system:
      enabled:
        - sddm.service
        - nvidia-persistenced.service

  - type: default-uids
    min-uid: 1000

  - type: files
    files:
      - source: system
        destination: /
  
